### PR TITLE
trying to fix scroll on table

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR fixes a few small errors in some PT lessons but is mostly concerned with trying to fix the scroll on a table in a french lesson. 

Weirdly enough if you write the css inline on the element the scroll works, but if you inspect the element it is not inheriting the class like it should.

1000 internet points to whomever figures out why that's happening 😅

### CODE REVIEW

**Comment by spapastamkou** [comment]
@ZoeLeBlanc I made some additions to the code but in the meantime the table went scrollable (after [#2503](https://github.com/programminghistorian/jekyll/issues/2503) merge). I close this without merging but let me know if you want me to do something else here. Thanks a lot!

**Comment by jenniferisasi** [comment]
🤔🤔🤔

Sofia had tried the ``` and html tag at the beginning, but then was showing raw markdown, etc. What neither of us had included was the "style="overflow:auto;" part! 

Screen Shot 2022-03-03 at 9 18 24 AM

In any case, thanks for the last "touch" @ZoeLeBlanc!

**Comment by ZoeLeBlanc** [comment]
Ya actually I wanted to keep this PR open because writing styles directly on to HTML elements is not great... like the CSS should be inherited on to the element and it's not, so we need to figure out why 😅 . So my fix is not a permanent fix is what I'm saying...

**Comment by spapastamkou** [comment]
oh, sorry:) I keep an eye here, if you want me to undo the latest commit adding backticks and html, let me know!

**Comment by ZoeLeBlanc** [comment]
Not your fault at all @spapastamkou ! Realize I should've made this a draft PR so there would be less confusion, so mea culpa! Mostly I'm hoping we can find a solution that doesn't require inline CSS so that we can use it for future tables. But I'll give it a few days and if no one has any ideas, we'll just close this and leave it as is 👍🏽

**Comment by jenniferisasi** [comment]
> Ya actually I wanted to keep this PR open because writing styles directly on to HTML elements is not great... like the CSS should be inherited on to the element and it's not, so we need to figure out why 😅 . So my fix is not a permanent fix is what I'm saying...

Right. And also realized that already published tables, when making the screen thin, they won't have the scroll bar, so the information "hides" so to speak. SO it would be very good if we can find an "automatic" solution that puts the scroll bar in any table when the screen requires so.

**Pull request merged**
