### PR TITLE
Re-organising the /pt directory

### LINKED ISSUE #535: Re-organising the PT file directories within ph-submissions
I am re-organising the PT file directories within ph-submissions.
--

_I would like to apologise for the extended delay in bringing this directory into alignment with the others_

--

N.B. I am aware that these changes will break links to live Lesson Previews, so my first task after merging will be:

- update all Preview links for lessons under active review
- let all active editors, authors and reviewers know that the file directory structure has changed for PT

In collaboration with @DanielAlvesLABDH and @JimmyMedeiros82, I have created two sub-folders within the directory /pt:

/pt/esbocos/
/pt/publicadas/

Nested within those, I have created:

/pt/esbocos/traducoes
/pt/esbocos/originais

/pt/publicadas/traducoes
/pt/publicadas/originais

--

At the same time, I have cleared/moved all loose items from the /lessons directory which is no longer in use.

I have made the following changes

> /lessons
>
> /lessons/portuguese/propostas/
> /lessons/portuguese/propostas/ocr-e-traducao-automatica.md
> Moved to >> /pt/esbocos/traducoes/ocr-e-traducao-automatica.md
>
> /lessons/published
> /lessons/published/crowdsourced-data-normalization-with-pandas.md
> Moved to >> /en/published/originals/crowdsourced-data-normalization-with-pandas-2.md
> N.B. Renamed with -2 suffix as there was an existing .md with the same name in this folder
> 
> /lessons/spanish
> /lessons/spanish/_includes
> /lessons/spanish/_includes/footer.com
> Deleted >> this is an outdated file
> /lessons/spanish/_includes/header.md
> Deleted >> this is an outdated file
> 
> /lessons/spanish/lecciones
> /spanish/lecciones/escritura-sustentable-usando-pandoc-y-markdown.md
> Moved to >> /es/publicadas/traducciones/escritura-sustentable-usando-pandoc-y-markdown.md
> /spanish/lecciones/introduccion-a-markdown.md
> Moved to >> /es/publicadas/traducciones/introduccion-a-markdown-2.md
> N.B. Renamed with -2 suffix as there was an existing .md with the same name in this folder
> /spanish/lecciones/preservar-datos-de-investigacion.md
> Moved to >> /es/publicadas/traducciones/preservar-datos-de-investigacion-2.md
> N.B. Renamed with -2 suffix as there was an existing .md with the same name in this folder
> 
> /lessons/spanish/readme.md
> Deleted >> this is an outdated file
> 
> /lessons/enron_network_with_communities.png
> Moved to >> /images >> this is a loose image, which appears to have been associated with the lesson en/sentiment-analysis but was not used.
> 
> /lessons/lavorato-j.zip
> Moved to >> /assets >> this is a loose asset, which appears to have been associated with the lesson en/sentiment-analysis but was not used.
> 
> /lessons/out.html
> Moved to >> /en/published/originals/dealing-with-big-data-and-network-analysis-using-neo4j.html >> this is an html draft of a published en lesson
> N.B. Renamed for clarity
> 
> /lessons/sample-lesson.md
> Deleted >> this is an outdated file

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am re-organising the PT file directories within ph-submissions.

Closes #535

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes thank you for this organizing effort. It's not easy to put the Portuguese in order ;-)
Apart from the conflicting files, I took a look at the changes and all seems fine.

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH. I am working on resolving the conflicts! Thank you for your patience.

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc. Maybe we could look at this together when we connect next week too? I would really appreciate your guidance, (I'm keen to gain confidence re-basing branches within ph-submissions, as I can now do efficiently in Jekyll). 

--

Notes to myself:

Taking each of these conflicting files in turn:

pt/licoes/originais/sumarizacao-narrativas-web-python.md

> this has moved to /pt/esbocos/originais

pt/licoes/traducoes/aplicacao-web-interativa-r-shiny-leaflet.md

> this has moved to /pt/esbocos/traducoes/aplicacao-web-interativa-r-shiny-leaflet.md

pt/licoes/traducoes/autoria-sustentavel-texto-simples-pandoc-markdown.md

> I made a mistake with this one: it has not been published.
I am moving it now (02.12.22) to pt/esbocos/traducoes/autoria-sustentavel-texto-simples-pandoc-markdown.md

pt/licoes/traducoes/download-multiplos-registros-query-strings.md

> this lesson has been published since I did the re-organisation last Friday.
I am moving it now (02.12.22) to pt/publicadas/traducoes/download-multiplos-registros-query-strings.md

pt/licoes/traducoes/manipulacao-transformacao-dados-R.md

> this lesson has been published since I did the re-organisation last Friday.
I am moving it now (02.12.22) to pt/publicadas/traducoes/manipulacao-transformacao-dados-R.md

-- 

In the command line, I'm currently trying to navigate back to gh-pages so I can pull the latest changes into my branch. I am encountering a prompt that `pt/publicadas/traducoes/leitura-escalavel-dados-estruturados.md: needs merge`. This is a new file, which has been created since I did this work.

Screenshot 2022-12-02 at 14 26 29

Confusingly, if I click into my local drive I find it at /pt/publicadas/traducoes/leitura-escalavel-dados-estruturados.md ... but[ I didn't put it there in my branch](https://github.com/programminghistorian/ph-submissions/tree/pt-tidy-repo-11-22/pt/publicadas/traducoes).

**Comment by anisa-hawes** [comment]
Huge thank you to @ZoeLeBlanc and @jrladd for their support fixing these conflicts! ✨

**Pull request merged**
