### PR TITLE
Comentarios sección Acerca de

### PR DESCRIPTION
**Pull request by mariajoafana**
Hice algunos comments entre () e hice sugerencias para cambiar algunas palabras.

### CODE REVIEW

**Comment by arojascastro** [comment]
Ups! Tengo que revisar esto! Gracias @mariajoafana

**Comment by arojascastro** [comment]
How we can solve this @acrymble ? I think @mariajoafana commented on the landing page http://programminghistorian.org/es/ but we never took into consideration her feedback. However, I think she has double checked that page recently. What should we do to solve this conflict?

**Comment by acrymble** [comment]
You'll have to ask someone who is better at github. I have no idea.

**Comment by arojascastro** [comment]
No worries. I think I can deal with it. After including @mariajoafana's comments I will close this.

**Pull request closed without merging**
